### ISSUE TITLE
Moving to the new Org mode repsoitory

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#102]
We are moving to the new Org mode repository, I've set a tentative final move date of the middle of the year, 06-15-2022 // 2022-06-15.

  Which files to we keep?  I added *most* of the .md [Markdown] files that I would consider basic metadata for our group.  
the /website/ folder is a seperate project. @Mahad410 @NaincyKumariKnoldus @HritikR @idormain @mckinnon81 
  
  If you haven't gotten an invite to the repository, let me know.  @idormain @callowcreation @mckinnon81 @swathe 

  I intend on creating Teams.   Primarily a website team.

**Comment by HritikR** [comment]
@gbowne1  After moving to the new Org-mode repository we should consider working on different branches and sending PR rather than directly sending commits to the master branch.🤔

**Comment by gbowne1** [comment]
That's a great idea @HritikR.  

At least to me, Ideally there would be branches called:

{main} working tree 
{master} permanent // not to be messed with ;; staged for production // releases.
{test} stuff that is not suited for either {main} or {test} branch or for testing purposes, stuff that may or may not work.
{feature} branches for specific features

Here main and master could be switched.

I'm assuming that this is how this is normally done. I could be wrong but I doubt we would need other branches.

Might also be something like this: 

    Master {working branch??}
    Feature branch (aka Topic branch) for example when we implement blog to the website, it would get it's own branch.
    Release branch {main or master?}
    Hotfix branch {triage fixed bugs} i.e. snippits/gists of stuff that are used to fix bugs.
    Develop branch  (Integration branch)
    User Branches that would look something like:
            users/username/description
            users/username/workitem
    (these would be code from specific task assignments) i.e. /users/HritikR/{item}

The documentation for this needs to go into https://github.com/taotnpwaft/docs/  just make sure it's some form of .pdf, .md, .doc/.docx, .odt or .md file.  

I would like to keep the repository clean of random branches 

I've assigned you and @Mahad410 to the website Team on the new repository.    

thoughts, @idormain @HritikR @Mahad410 ??

**Comment by gbowne1** [comment]
I am also thinking of adding at least one merge reviewer.

As for directly committing and pushing to the master branch, we've been doing that so far because not enough site structure actually works well enough yet.. and most changes have worked.  I've been waiting on getting enough built and working to move forwards with processes.  Not enough has been set in stone for the org yet.  I'm open to whomever wants to write those docs and put them in the docs repo in the org.

**Comment by gbowne1** [comment]
This TODO and  issue was moved to the new Org repository.
