### ISSUE TITLE
Create a logo for group and website to replace the current one.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#25]
We do have a logo currently but there are some issues with it. That logo I threw together quickly using a free online generator.  I am no artist though.

It does not look great on our website at 1920x1080.
I doubt it would look great on mobile.

We really need a new set of artwork, logos, thumbnails in .jpg, .png, .svg and .ico especially for our website.

**Comment by idormain** [comment]
Hire from fivrr. Logo development is generally cheap. Must ensure contractually we own the IP.

**Comment by gbowne1** [comment]
Good idea.  There are lots of creators on sites like UpWork, Fiverr, etc.

Facebook also needs a set of graphics.  The current banner image is just a placeholder for a better image.

Yeah, we will have to make sure we legally and contractually own the IP.

We do have some funds available for this.  

This brings the question, how do we decide who has the skills so thar we get the best possible images, etc.  What criteria do we use? And attain assuredness that they won't just use stock images.

**Comment by gbowne1** [comment]
Facebook Requires: 
   820 pixels wide by 312 pixels tall on desktop. However, mobile users will see 640 pixels wide by 360 pixels tall. The Aspect ratio is 16:9 and the Group Cover banner is supposed to be 1640 x 856 pixels.
