### ISSUE TITLE
Create new or refactor Bug Report and Feature Request files into .yml

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#30]
Github has deprecated the use of .md [Markdown] files in the .github/ISSUE_TEMPLATE/ folder and changed to YAML .yml front-matter.

There is also a configuration file `config.yml` that tells Github how to to use the file(s) that goes into this directory.  

The current  files are all .md in this folder.

see: [Issue Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by RishiKumarRay** [comment]
I would like to do this , Assignme

**Comment by gbowne1** [comment]
@RishiKumarRay,

   Do you have experience with refactoring .md into YAML/.yml?  or with YAML?

**Comment by RishiKumarRay** [comment]
Yeah i have made issue templates in Yaml recently , Do you want me to make new one or refector this md into yaml?

**Comment by gbowne1** [comment]
Ok, It would be great if you could please refactor and also make sure the config.yml is correct.

**Comment by RishiKumarRay** [comment]
Sure i will try my best

**Comment by gbowne1** [comment]
@RishiKumarRay have you had any luck with this yet?

**Comment by gbowne1** [comment]
This was moved to the new org mode repository.
