### ISSUE TITLE
[TODO] Website - Blog Functionality

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#36]
I have made a folder in this repository called /website/blog/ and this section will house the blog functionality.. and the main rendered page will be blog.html (or should it be blog.php or blog.js)

Most blog websites have been made with PHP, Javascript, jQuery and Ajax.  Examples are Wordpress, LiveJournal, Blogger..

What type of functionality do we need to inherit?

Posts:
 - Add Posts
 - Edit Posts
 - Delete Post
 - Moderation features (ban, etc)
 - Commenting
 - Adding media (pics, etc)
 - ?

**Comment by warisreshi** [comment]
You can add things like a author system if you want, It may need a login/register system in PHP and MYSQL.

**Comment by gbowne1** [comment]
The site will have login and register by itself.  Would the blog use a separate login & register in order to inherit the author system?

Is there a library?

**Comment by gbowne1** [comment]
I was thinking it might be possible to cache our blog entries as simple HTML snippets and then the other content / images, in something like AWS S3 buckets, and load them using purely javascript via AJAX or make life easier with jQuery or another JS framework served from a CDN. This avoids the need for PHP and MySQL entirely, but since we are using them..

**Comment by gbowne1** [comment]
This might be useful.  Some MySQL for blogs.

https://mysql.tutorials24x7.com/blog/guide-to-design-a-database-for-blog-management-in-mysql

**Comment by gbowne1** [comment]
@HritikR @Mahad410
