### ISSUE TITLE
[TODO] IIS & Server Configuration

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#46]
[TODO] Add IIS server configuration

**Comment by gbowne1** [comment]
It might be useful to create the Powershell etc to help manage the server.

**Comment by idormain** [comment]
Powershell is great, but it’s great in multi server environments where you have hundreds of servers. Do we really need to develop powershell to manage one server?

**Comment by gbowne1** [comment]
I don't know, @idormain , That's why I asked.  We aren't likely to have more than 4-5 servers and a storage array (MD1200, etc) at any one time.  

When I was using IIS Express locally I made a bunch of things to help me out with maintaining that.

**Comment by idormain** [comment]
Hiya

I thought initially there would be a single server running?

**Comment by gbowne1** [comment]
Yes to start with.  I cant see us having more than 4 or 5 to do anything we
need to do.  1 or 2 should be fine.

We may need a firewall machine though.
