### ISSUE TITLE
[TODO] Website - Light Mode/Dark Mode Theme Swtich

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#47]
[TODO] Light Mode/Dark Mode Theme Switch

Create a working light/dark theme switch.

**Comment by Trupti0406** [comment]
@gbowne1 I'd like to work on this issue. It'd be helpful if you give more details about the same, regarding where to add the theme switch. Please assign this task to me.

**Comment by gbowne1** [comment]
@Trupti0406
 Thanks.  Put the theme switch in the black horizontal navbar in an appropriate place.

We are using the convention .TAOT for styling so for a theme it would be something like .TAOTtheme or .TAOTTheme
