### ISSUE TITLE
[TODO] Website - Admin Panel

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#48]
[TODO] Admin panel for website

I have inserted a stub of code for admin panel for the site and the blog inside website/admin.html

**Comment by idormain** [comment]
Shouldn’t we know what functions requiring an admin panel there are?

**Comment by gbowne1** [comment]
@idormain yes.  The blog page will need a admin panel. If not, a way to edit posts, commenting, etc.   The same goes for the rest of the site, since we likely will have logged in users, etc.

**Comment by idormain** [comment]
Hi Greg 

Ok, editing, adding and deleting blogs say. This functionality seems more in line with a CMS? Are we going to be building a quasi CMS?

Cheers 

Ivan

**Comment by idormain** [comment]
Hiya

I guess do we build the site from scratch or do we use something like Wordpress and code our features?

**Comment by gbowne1** [comment]
Quasi CMS.. probably.  The site itself will need some similar functionality, not just the blog and things in its Database.  

Most blog pages and blog sites have a means of managing this.  Keep in mind /blog.html page on our site would be a significant portion of our site content.. however not all of it 

A person/user intending to read notififcations, comment on blog posts, edit posts, like and share, create new users, editing user profiles, security & moderation things like banning, etc.

I can imagine Ivan or myself or our members posting about some project, code, a tutorial on something, a review, etc.

**Comment by gbowne1** [comment]
I would say continue building it from scratch.  I had considered Wordpress only if we couldnt manage to get something working

**Comment by gbowne1** [comment]
Most of what Wordpress and others does is interact with the DB anyhow.  Shouldnt be that hard.

**Comment by gbowne1** [comment]
Quoted from a good friend of mine. "Use a tool like PHP that allows dynamic generation of web pages.

You would create a page with a form that allows you to add a blog post: it gives title, content, and perhaps author name and date and time to display.

That page would take the information you wrote on the form and write it as a record on the database, for example, to a POSTS table.

In the simplest case, your blog page might simply read the posts from newest to oldest, and put the first 10 (say) on a page that is dynamically generated using PHP or other tool. Real blogs have some feature that parses the URL of a page on your site and determines which page or pages to display based on that URL. For example, http://www.myblog.com/my-vacation might display a blog post titled “My Vacation.” One way that is done is by using the .htaccess file ".

There is also a framework called Ghost in JS.

**Comment by idormain** [comment]
Hiya 

Yes, I understand about CMS and databases, also, we should try to limit the number of libraries being used. 

Cheers

Ivan

**Comment by gbowne1** [comment]
Yeah, that's fine @idormain It's available as needed.  

i'll stick this here for reference and as an option 
- https://ghost.org/docs/content-api/
- https://ghost.org/docs/content-api/javascript/
- https://ghost.org/docs/admin-api/javascript/
- https://ghost.org/docs/admin-api/

I agree about limiting the libraries.  However we're not likely to need much more than we already have.

**Comment by gbowne1** [comment]
Here's a Codepen of a Admin panel with some of the functionality needed:

https://codepen.io/melissacabral/pen/ZbPWEJ

**Comment by gbowne1** [comment]
@HritikR @Mahad410
