### ISSUE TITLE
[TODO] clean up the TAOT.css file

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#49]
[TODO] clean up the main CSS File, TAOT.css.

- Add mobile views and @media queries for common mobile devices and browsers.

- Fix issue with [register] and [login] button separation on navigation bar under the jumbotron.

- Move the X [Close] button for left side navigation drawer to a better location.

**Comment by gbowne1** [comment]
Add colors and styling to Social Media icons on main page.

**Comment by Trupti0406** [comment]
@gbowne1 I'd like to work on this issue. Please assign it to me.

**Comment by gbowne1** [comment]
@Trupti0406 

 I would appreciate any help with this you can provide. 

We are using the convention .TAOT for the styling as you can see in the TAOT.css file.

**Comment by gbowne1** [comment]
I did some research on @media queries for mobile views and should fit:

Height:  values 360 through 430
Width: values 470 through 926

For a tablet it seems that 600 to 800 x 1080 to1280 should be good at 100%.
This may exclude the Kindle.

**Comment by gbowne1** [comment]
This issue has largely been fixed with recent commits / push.
