### ISSUE TITLE
[TODO] Website - Move the <script> tags to the end of the HTML for faster loading

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#51]
[TODO]
   Move the <script></script> tags from the head to the end of the HTML for faster loading.
  
  > index.html
 
  Also remove the extra CDN links to Bootstrap and FontAwesome in the <head>

**Comment by NaincyKumariKnoldus** [comment]
Hey @gbowne1 Can I do this please?

**Comment by Ritul2112** [comment]
@gbowne1 I can help..

**Comment by gbowne1** [comment]
@NaincyKumariKnoldus I can assign you this task.

**Comment by NaincyKumariKnoldus** [comment]
sure @gbowne1 I will do this. thanks!

**Comment by NaincyKumariKnoldus** [comment]
Hey @gbowne1 Can you please review my PR.

**Comment by gbowne1** [comment]
Good work @NaincyKumariKnoldus, thanks for the opportunity to review your PR.  I've merged your PR moving the scripts from the head and tested.  All good.
