### ISSUE TITLE
[TODO] Website - Styling contact form

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#61]
Styling for contact form is incorrect

Should be added to the TAOT.css

This might be good as a card, popper, container, modal or flexbox.

Use Bootstrap, FontAwesome, Popper?

**Comment by gbowne1** [comment]
The About page on about.html also doesn't seem to render the same as index.html

**Comment by Mahad410** [comment]
I want to contribute to your project so I want you to believe in me.

**Comment by gbowne1** [comment]
@Mahad410 you are welcome to work on it. We will review your PR, if it looks good and works it will be merged.  Thanks for the request.

**Comment by Mahad410** [comment]
> @Mahad410 you are welcome to work on it. We will review your PR, if it looks good and works it will be merged. Thanks for the request.

It's already done you can check it and I want to contribute more.

**Comment by gbowne1** [comment]
I did not see a pull request from you @Mahad410

**Comment by Mahad410** [comment]
check again
