### ISSUE TITLE
[TODO] Website - Content move right on click hamburger drawer nav

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#68]
This may or may not be a 'thing' but when the drawer opens the content does not move to the right so the drawer nav panel covers the left side of the content.

Needs a method to push the content to the right when the hamburger gets clicked.

**Comment by Mahad410** [comment]
I will work on it

**Comment by gbowne1** [comment]
Ok @Mahad410.  Thanks.

**Comment by gbowne1** [comment]
@Mahad410 That would be most of them in /website/ but mainly index.html here:

https://github.com/gbowne1/taotnpwaft/blob/master/website/index.html

**Comment by gbowne1** [comment]
@Mahad410 how are you going on with this issue?

**Comment by Mahad410** [comment]
@gbowne1 i have final exams thats why i didnt completeed it yet but next month i can complete it for sure

**Comment by gbowne1** [comment]
Ok, keep me updated @Mahad410.

**Comment by Mahad410** [comment]
> Ok, keep me updated @Mahad410.

sure now my exams are over so I am ready to work...👀

**Comment by Mahad410** [comment]
why do you want to shift the content I mean when the user opens the sidebar he is not looking at content

**Comment by Mahad410** [comment]
and i fixed the layout of the page

**Comment by gbowne1** [comment]
Great, well hopefully you can help finish some of the TODO issues I have added.

I am pretty sure most users would expect a clean user experience.  Yeah the user is likely not focusing on the content, while the drawer/panel is open.

What did you change?  I look forwards to reviewing your PR.

**Comment by Mahad410** [comment]
> Great, well hopefully you can help finish some of the TODO issues I have added.
> 
> I am pretty sure most users would expect a clean user experience. Yeah the user is likely not focusing on the content, while the drawer/panel is open.
> 
> What did you change? I look forwards to reviewing your PR.

already push it to your repository you can check it

**Comment by gbowne1** [comment]
I just got back to my office.  That looks great.  I will close this issue.  I have not specifically decided on actual front page content on the index.html

Have you decided on what else you'd like to work on?

**Comment by Mahad410** [comment]
> I just got back to my office. That looks great. I will close this issue. I have not specifically decided on actual front page content on the index.html
> 
> Have you decided on what else you'd like to work on?

I will take a break here Ummm I just fix this issue because I told you that I will work on it after my exams so I will take some days off and then I will think.....lol
