### ISSUE TITLE
[TODO] Website - Fix Blog rendering 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#73]
/website/blog/blog.html is not rendering correctly.  It should be basically the same as website/index.html

It currently renders like this:

![Screenshot 2022-02-08 at 15-16-29 The Art of Tech Not Playing with a Full Tech](https://user-images.githubusercontent.com/47549872/153091981-819c66cb-4a10-44e0-9dab-09fdb6265dd5.png)

**Comment by omkarg01** [comment]
@gbowne1 I would like to work on this issue.

**Comment by gbowne1** [comment]
@omkarg01 you are welcome to work on this.

**Comment by omkarg01** [comment]
@gbowne1 How can I reproduce it?

**Comment by gbowne1** [comment]
@omkarg01 I don't know, but website/index.html renders fine. So you might use that to start over.

**Comment by omkarg01** [comment]
Where is the difference? 
![greg](https://user-images.githubusercontent.com/67428719/153651176-e51ab390-0a57-4563-83db-cd027523fa88.png)
I can see that /website/blog/blog.html is rendering as what website/index.html should be.

**Comment by gbowne1** [comment]
@omkarg01

 ![Screenshot_2022-02-10_at_22-05-51_The_Art_of_Tech_Not_Playing_with_a_Full_Tech](https://user-images.githubusercontent.com/47549872/153657552-b97f5073-76b0-4760-bdb0-a16f037a6bc8.png)

This is how it should render.

**Comment by gbowne1** [comment]
I fixed this.. it was a problem with the TAOT.css not being found.
