### ISSUE TITLE
[TODO] Website - Fix broken User Profile

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#74]
[TODO] Website

Fix the broken user profile and its layout.

Add "Profile" to left navigation drawer

Also current data displayed is not dynamic.

Files:
https://github.com/gbowne1/taotnpwaft/blob/master/website/profile.html
https://github.com/gbowne1/taotnpwaft/blob/master/website/profile.css

**Comment by Mahad410** [comment]
Can you explain this to me and I would like to work on this

**Comment by gbowne1** [comment]
Ok @Mahad410 .  I will update the TAOTSite.drawio file.

Here is the current render of the file taotnwpaft/website/profile.html
![Screenshot 2022-02-24 at 13-58-26 User Profile](https://user-images.githubusercontent.com/47549872/155615035-ef7a8564-53fc-49a3-b992-0d802563ae34.png)

It's currently quite a mess.
- The two panels are not responsive
-  its not dynamic either 
-  currently no way to edit it profiles.  It should bring the user data from the MySQL database 
-  too much whitespace.

There is a duplicate issue with more information: https://github.com/gbowne1/taotnpwaft/issues/54

**Comment by Mahad410** [comment]
I cant fix fetching data because for that we need PHP which I am currently learning

**Comment by gbowne1** [comment]
@Mahad410 I can do the PHP part.
