### ISSUE TITLE
[TODO] Login

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#81]
When logged in main page should show a popper, modal or a toast notification that says "Hello [or Welcome], {<username>}!" and/or as well as successful login.  

Admin login should show user logged in as admin, possibly a time/date stamp.
New user:  {possibly a new user welcome [splash} page?}
Returning user: Welcome back the returning user

Note: Bootstrap 5 has toasts: 
https://getbootstrap.com/docs/5.1/components/toasts/
https://www.w3schools.com/bootstrap5/bootstrap_toast.php

Current Login modal {below] is a little hard to read but works.  Can barely see the word "Login" at the top of the modal. 
The icons on the left of the fields are not the same size 
![Screenshot 2022-03-05 at 19-24-29 The Art of Tech Not Playing with a Full Tech](https://user-images.githubusercontent.com/47549872/156907900-cc4b9894-9c02-4bf8-8636-0e6c713a3a10.png)

**Comment by adkood** [comment]
please assign me this task.

**Comment by gbowne1** [comment]
@adkood are you sure that youll be able to do this one?

**Comment by gbowne1** [comment]
Chrome complains about:

> [DOM] Password field is not contained in a form:

in the modal.  I did not see this in Firefox 97 console.

**Comment by gbowne1** [comment]
Recent push fixed the styling of the modal., but other issues remain.

**Comment by gbowne1** [comment]
This issue was fixed with recent commit from @HritikR #95
